import express from 'express';
import { createServer } from 'http';
import { Server } from 'socket.io';
const app=express(); const http=createServer(app); const io=new Server(http,{cors:{origin:'*'}}); app.use(express.json());
const quote=(km:number,base=3000)=>({currency:'UGX',distanceKm:km,fee:base+Math.ceil(km)*1000,etaMinutes:Math.ceil(km*5)+10});
app.get('/api/health',(_,res)=>res.json({ok:true,service:'quickdrop-ug'}));
app.get('/api/courier/quote',(req,res)=>res.json(quote(Number(req.query.km)||2)));
app.post('/api/orders/courier',(req,res)=>{const distance=Number(req.body.distance)||2;res.status(201).json({id:'QD-C'+Date.now().toString().slice(-5),type:'courier',status:'searching',deliveryFee:quote(distance).fee,...req.body});});
app.get('/api/ride/quote',(req,res)=>res.json({currency:'UGX',distanceKm:Number(req.query.km)||4,fares:{'Boda Boda':6500,TukTuk:8500,Car:12000}}));
app.post('/api/ride/book',(req,res)=>res.status(201).json({id:'QD-R'+Date.now().toString().slice(-5),status:'searching',...req.body}));
app.patch('/api/rides/:id/status',(req,res)=>res.json({id:req.params.id,status:req.body.status}));
app.get('/api/food',(_,res)=>res.json({restaurants:6}));
io.on('connection',socket=>{socket.on('join-trip',id=>socket.join(`trip:${id}`));socket.on('location-update',data=>io.to(`trip:${data.tripId}`).emit('location-update',data));socket.on('chat',data=>io.to(`trip:${data.tripId}`).emit('chat',data));});
http.listen(process.env.PORT||4000,()=>console.log('QuickDrop API running on :4000'));
