'use client';
import { useMemo, useState } from 'react';
import { Camera, MapPin, Package, ShieldCheck } from 'lucide-react';
import Link from 'next/link';

const formatUGX=(amount:number)=>`UGX ${amount.toLocaleString('en-UG')}`;
export default function CourierPage(){
 const [distance,setDistance]=useState(2); const [submitted,setSubmitted]=useState(false);
 const total=3000+Math.ceil(distance)*1000;
 const quote=useMemo(()=>({distance, total}),[distance,total]);
 if(submitted)return <Success id="QD-C4821"/>;
 return <main className="mx-auto max-w-5xl px-5 pb-16"><Header title="Courier service" subtitle="Send documents and parcels across Kampala with live tracking."/><div className="grid gap-6 lg:grid-cols-[1fr_.72fr]"><form className="card space-y-5 p-6" onSubmit={e=>{e.preventDefault();setSubmitted(true)}}><div className="grid gap-4 sm:grid-cols-2"><Field label="Pickup address" placeholder="Pickup address 📍"/><Field label="Dropoff address" placeholder="Dropoff address 📍"/></div><div className="grid gap-4 sm:grid-cols-2"><Field label="Sender name" placeholder="Full name"/><Field label="Sender phone" placeholder="07XX XXX XXX" type="tel"/><Field label="Receiver name" placeholder="Full name"/><Field label="Receiver phone" placeholder="07XX XXX XXX" type="tel"/></div><div className="grid gap-4 sm:grid-cols-2"><label className="text-sm font-bold">Package type<select className="field mt-2"><option>Document</option><option>Small</option><option>Medium</option><option>Large</option></select></label><label className="text-sm font-bold">Weight<input className="field mt-2" placeholder="e.g. 2 kg"/></label></div><label className="flex cursor-pointer items-center gap-3 rounded-2xl border border-dashed border-black/15 p-4 text-sm font-bold"><Camera size={20} className="text-leaf"/> Add package photo<input type="file" accept="image/*" className="hidden"/></label><button className="btn-primary w-full">Create courier order</button></form><aside className="rounded-3xl bg-[#eff8e3] p-6"><Package className="text-leaf"/><p className="mt-6 text-sm font-bold text-leaf">PRICE CALCULATOR</p><p className="mt-2 text-5xl font-black">{formatUGX(quote.total)}</p><p className="mt-2 text-sm text-slate-500">UGX 3,000 base + UGX 1,000 per km</p><label className="mt-8 block text-sm font-bold">Estimated distance<input type="range" min="1" max="25" value={distance} onChange={e=>setDistance(Number(e.target.value))} className="mt-3 w-full accent-[#0d5c48]"/><span className="mt-2 block text-slate-500">{distance} km · 25–35 min</span></label><div className="mt-8 rounded-2xl bg-white p-4 text-sm"><p className="flex justify-between"><span>Base fare</span><b>{formatUGX(3000)}</b></p><p className="mt-2 flex justify-between"><span>Distance fee</span><b>{formatUGX(Math.ceil(distance)*1000)}</b></p></div></aside></div></main>;
}
function Header({title,subtitle}:{title:string;subtitle:string}){return <div className="mb-8"><Link href="/" className="text-sm font-bold text-slate-500">← Back home</Link><h1 className="mt-5 text-4xl font-black">{title}</h1><p className="mt-2 text-slate-500">{subtitle}</p></div>}
function Field({label,placeholder,type='text'}:{label:string;placeholder:string;type?:string}){return <label className="block text-sm font-bold">{label}<input required type={type} className="field mt-2" placeholder={placeholder}/></label>}
function Success({id}:{id:string}){return <main className="mx-auto max-w-xl px-5 pb-16"><div className="card p-8 text-center"><div className="mx-auto grid h-16 w-16 place-items-center rounded-full bg-lime text-leaf"><ShieldCheck/></div><h1 className="mt-5 text-3xl font-black">Courier order created</h1><p className="mt-2 text-slate-500">Your order <b>{id}</b> is searching for a rider.</p><Link className="btn-primary mt-6 inline-block" href={`/tracking/${id}`}>Track courier</Link></div></main>}
